<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class CustomFieldsGroupsTypeSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $data = [
            [
                'form_type' => '1',
                'group_id' => null,
                'wf_type_id' => 5,
                'custom_field_id' => 27,
                'sort' => 3,
                'active' => '1',
                'created_at' => '2025-12-30 09:37:07',
                'updated_at' => '2025-12-30 09:37:07',
                'validation_type_id' => 1,
                'enable' => 1,
                'status_id' => null,
            ],
            [
                'form_type' => '1',
                'group_id' => null,
                'wf_type_id' => 5,
                'custom_field_id' => 28,
                'sort' => 5,
                'active' => '1',
                'created_at' => '2025-12-30 09:37:07',
                'updated_at' => '2025-12-30 09:37:07',
                'validation_type_id' => 1,
                'enable' => 1,
                'status_id' => null,
            ],
            [
                'form_type' => '1',
                'group_id' => null,
                'wf_type_id' => 5,
                'custom_field_id' => 29,
                'sort' => 10,
                'active' => '1',
                'created_at' => '2025-12-30 09:37:07',
                'updated_at' => '2025-12-30 09:37:07',
                'validation_type_id' => 1,
                'enable' => 1,
                'status_id' => null,
            ],
            [
                'form_type' => '1',
                'group_id' => null,
                'wf_type_id' => 5,
                'custom_field_id' => 30,
                'sort' => 20,
                'active' => '1',
                'created_at' => '2025-12-30 09:37:07',
                'updated_at' => '2025-12-30 09:37:07',
                'validation_type_id' => 1,
                'enable' => 1,
                'status_id' => null,
            ],
            [
                'form_type' => '1',
                'group_id' => null,
                'wf_type_id' => 5,
                'custom_field_id' => 33,
                'sort' => 30,
                'active' => '1',
                'created_at' => '2025-12-30 09:37:07',
                'updated_at' => '2025-12-30 09:37:07',
                'validation_type_id' => null,
                'enable' => 0,
                'status_id' => null,
            ],
            [
                'form_type' => '1',
                'group_id' => null,
                'wf_type_id' => 5,
                'custom_field_id' => 34,
                'sort' => 5,
                'active' => '1',
                'created_at' => '2025-12-30 09:37:07',
                'updated_at' => '2025-12-30 09:37:07',
                'validation_type_id' => 1,
                'enable' => 1,
                'status_id' => null,
            ],
            [
                'form_type' => '1',
                'group_id' => null,
                'wf_type_id' => 5,
                'custom_field_id' => 35,
                'sort' => 35,
                'active' => '1',
                'created_at' => '2025-12-30 09:37:07',
                'updated_at' => '2025-12-30 09:37:07',
                'validation_type_id' => 1,
                'enable' => 1,
                'status_id' => null,
            ],
            [
                'form_type' => '1',
                'group_id' => null,
                'wf_type_id' => 5,
                'custom_field_id' => 36,
                'sort' => 15,
                'active' => '1',
                'created_at' => '2025-12-30 09:37:07',
                'updated_at' => '2025-12-30 09:37:07',
                'validation_type_id' => 3,
                'enable' => 1,
                'status_id' => null,
            ],
            [
                'form_type' => '1',
                'group_id' => null,
                'wf_type_id' => 5,
                'custom_field_id' => 38,
                'sort' => 30,
                'active' => '1',
                'created_at' => '2025-12-30 09:37:07',
                'updated_at' => '2025-12-30 09:37:07',
                'validation_type_id' => null,
                'enable' => 1,
                'status_id' => null,
            ],
            [
                'form_type' => '1',
                'group_id' => null,
                'wf_type_id' => 5,
                'custom_field_id' => 72,
                'sort' => 40,
                'active' => '1',
                'created_at' => '2025-12-30 09:37:07',
                'updated_at' => '2025-12-30 09:37:07',
                'validation_type_id' => null,
                'enable' => 1,
                'status_id' => null,
            ],
            [
                'form_type' => '1',
                'group_id' => null,
                'wf_type_id' => 5,
                'custom_field_id' => 82,
                'sort' => 45,
                'active' => '1',
                'created_at' => '2025-12-30 09:37:07',
                'updated_at' => '2025-12-30 09:37:07',
                'validation_type_id' => null,
                'enable' => 1,
                'status_id' => null,
            ],
            [
                'form_type' => '1',
                'group_id' => null,
                'wf_type_id' => 5,
                'custom_field_id' => 105,
                'sort' => 25,
                'active' => '1',
                'created_at' => '2025-12-30 09:37:07',
                'updated_at' => '2025-12-30 09:37:07',
                'validation_type_id' => null,
                'enable' => 1,
                'status_id' => null,
            ],
            [
                'form_type' => '2',
                'group_id' => null,
                'wf_type_id' => 5,
                'custom_field_id' => 1,
                'sort' => 5,
                'active' => '1',
                'created_at' => '2025-12-30 09:42:01',
                'updated_at' => '2025-12-30 09:42:01',
                'validation_type_id' => 1,
                'enable' => 1,
                'status_id' => null,
            ],
            [
                'form_type' => '2',
                'group_id' => null,
                'wf_type_id' => 5,
                'custom_field_id' => 27,
                'sort' => 10,
                'active' => '1',
                'created_at' => '2025-12-30 09:42:01',
                'updated_at' => '2025-12-30 09:42:01',
                'validation_type_id' => null,
                'enable' => 0,
                'status_id' => null,
            ],
            [
                'form_type' => '2',
                'group_id' => null,
                'wf_type_id' => 5,
                'custom_field_id' => 28,
                'sort' => 15,
                'active' => '1',
                'created_at' => '2025-12-30 09:42:01',
                'updated_at' => '2025-12-30 09:42:01',
                'validation_type_id' => null,
                'enable' => 0,
                'status_id' => null,
            ],
            [
                'form_type' => '2',
                'group_id' => null,
                'wf_type_id' => 5,
                'custom_field_id' => 29,
                'sort' => 20,
                'active' => '1',
                'created_at' => '2025-12-30 09:42:01',
                'updated_at' => '2025-12-30 09:42:01',
                'validation_type_id' => null,
                'enable' => 0,
                'status_id' => null,
            ],
            [
                'form_type' => '2',
                'group_id' => null,
                'wf_type_id' => 5,
                'custom_field_id' => 30,
                'sort' => 25,
                'active' => '1',
                'created_at' => '2025-12-30 09:42:01',
                'updated_at' => '2025-12-30 09:42:01',
                'validation_type_id' => null,
                'enable' => 0,
                'status_id' => null,
            ],
            [
                'form_type' => '2',
                'group_id' => null,
                'wf_type_id' => 5,
                'custom_field_id' => 33,
                'sort' => 50,
                'active' => '1',
                'created_at' => '2025-12-30 09:42:01',
                'updated_at' => '2025-12-30 09:42:01',
                'validation_type_id' => null,
                'enable' => 0,
                'status_id' => null,
            ],
            [
                'form_type' => '2',
                'group_id' => null,
                'wf_type_id' => 5,
                'custom_field_id' => 34,
                'sort' => 2,
                'active' => '1',
                'created_at' => '2025-12-30 09:42:01',
                'updated_at' => '2025-12-30 09:42:01',
                'validation_type_id' => null,
                'enable' => 0,
                'status_id' => null,
            ],
            [
                'form_type' => '2',
                'group_id' => null,
                'wf_type_id' => 5,
                'custom_field_id' => 35,
                'sort' => 55,
                'active' => '1',
                'created_at' => '2025-12-30 09:42:01',
                'updated_at' => '2025-12-30 09:42:01',
                'validation_type_id' => null,
                'enable' => 0,
                'status_id' => null,
            ],
            [
                'form_type' => '2',
                'group_id' => null,
                'wf_type_id' => 5,
                'custom_field_id' => 36,
                'sort' => 35,
                'active' => '1',
                'created_at' => '2025-12-30 09:42:01',
                'updated_at' => '2025-12-30 09:42:01',
                'validation_type_id' => null,
                'enable' => 0,
                'status_id' => null,
            ],
            [
                'form_type' => '2',
                'group_id' => null,
                'wf_type_id' => 5,
                'custom_field_id' => 38,
                'sort' => 40,
                'active' => '1',
                'created_at' => '2025-12-30 09:42:01',
                'updated_at' => '2025-12-30 09:42:01',
                'validation_type_id' => null,
                'enable' => 0,
                'status_id' => null,
            ],
            [
                'form_type' => '2',
                'group_id' => null,
                'wf_type_id' => 5,
                'custom_field_id' => 72,
                'sort' => 55,
                'active' => '1',
                'created_at' => '2025-12-30 09:43:26',
                'updated_at' => '2025-12-30 09:43:26',
                'validation_type_id' => null,
                'enable' => 1,
                'status_id' => 234,
            ],
            [
                'form_type' => '2',
                'group_id' => null,
                'wf_type_id' => 5,
                'custom_field_id' => 105,
                'sort' => 55,
                'active' => '1',
                'created_at' => '2025-12-30 09:43:26',
                'updated_at' => '2025-12-30 09:43:26',
                'validation_type_id' => null,
                'enable' => 1,
                'status_id' => 234,
            ],
            [
                'form_type' => '2',
                'group_id' => null,
                'wf_type_id' => 5,
                'custom_field_id' => 8,
                'sort' => 55,
                'active' => '1',
                'created_at' => '2025-12-30 09:48:16',
                'updated_at' => '2025-12-30 09:48:16',
                'validation_type_id' => null,
                'enable' => 1,
                'status_id' => 235,
            ],
            [
                'form_type' => '2',
                'group_id' => null,
                'wf_type_id' => 5,
                'custom_field_id' => 9,
                'sort' => 66,
                'active' => '1',
                'created_at' => '2025-12-30 09:48:16',
                'updated_at' => '2025-12-30 09:48:16',
                'validation_type_id' => null,
                'enable' => 1,
                'status_id' => 235,
            ],
            [
                'form_type' => '2',
                'group_id' => null,
                'wf_type_id' => 5,
                'custom_field_id' => 67,
                'sort' => 44,
                'active' => '1',
                'created_at' => '2025-12-30 09:48:16',
                'updated_at' => '2025-12-30 09:48:16',
                'validation_type_id' => 1,
                'enable' => 1,
                'status_id' => 235,
            ],
            [
                'form_type' => '2',
                'group_id' => null,
                'wf_type_id' => 5,
                'custom_field_id' => 105,
                'sort' => 77,
                'active' => '1',
                'created_at' => '2025-12-30 09:48:16',
                'updated_at' => '2025-12-30 09:48:16',
                'validation_type_id' => null,
                'enable' => 1,
                'status_id' => 235,
            ],
            [
                'form_type' => '1',
                'group_id' => null,
                'wf_type_id' => 1,
                'custom_field_id' => 106,
                'sort' => 62,
                'active' => '1',
                'created_at' => '2025-12-30 09:59:19',
                'updated_at' => '2025-12-30 09:59:19',
                'validation_type_id' => null,
                'enable' => 1,
                'status_id' => null,
            ],
            [
                'form_type' => '2',
                'group_id' => null,
                'wf_type_id' => 5,
                'custom_field_id' => 8,
                'sort' => 55,
                'active' => '1',
                'created_at' => '2025-12-30 10:02:29',
                'updated_at' => '2025-12-30 10:02:29',
                'validation_type_id' => null,
                'enable' => 1,
                'status_id' => 237,
            ],
            [
                'form_type' => '2',
                'group_id' => null,
                'wf_type_id' => 5,
                'custom_field_id' => 9,
                'sort' => 44,
                'active' => '1',
                'created_at' => '2025-12-30 10:02:29',
                'updated_at' => '2025-12-30 10:02:29',
                'validation_type_id' => null,
                'enable' => 1,
                'status_id' => 237,
            ],
            [
                'form_type' => '2',
                'group_id' => null,
                'wf_type_id' => 5,
                'custom_field_id' => 67,
                'sort' => 77,
                'active' => '1',
                'created_at' => '2025-12-30 10:02:29',
                'updated_at' => '2025-12-30 10:02:29',
                'validation_type_id' => null,
                'enable' => 0,
                'status_id' => 237,
            ],
            [
                'form_type' => '2',
                'group_id' => null,
                'wf_type_id' => 5,
                'custom_field_id' => 105,
                'sort' => 99,
                'active' => '1',
                'created_at' => '2025-12-30 10:02:29',
                'updated_at' => '2025-12-30 10:02:29',
                'validation_type_id' => null,
                'enable' => 0,
                'status_id' => 237,
            ],
            [
                'form_type' => '2',
                'group_id' => null,
                'wf_type_id' => 5,
                'custom_field_id' => 106,
                'sort' => 88,
                'active' => '1',
                'created_at' => '2025-12-30 10:02:29',
                'updated_at' => '2025-12-30 10:02:29',
                'validation_type_id' => null,
                'enable' => 1,
                'status_id' => 237,
            ],
            [
                'form_type' => '2',
                'group_id' => null,
                'wf_type_id' => 5,
                'custom_field_id' => 8,
                'sort' => 77,
                'active' => '1',
                'created_at' => '2025-12-30 10:29:55',
                'updated_at' => '2025-12-30 10:29:55',
                'validation_type_id' => null,
                'enable' => 1,
                'status_id' => 239,
            ],
            [
                'form_type' => '2',
                'group_id' => null,
                'wf_type_id' => 5,
                'custom_field_id' => 9,
                'sort' => 88,
                'active' => '1',
                'created_at' => '2025-12-30 10:29:55',
                'updated_at' => '2025-12-30 10:29:55',
                'validation_type_id' => null,
                'enable' => 1,
                'status_id' => 239,
            ],
            [
                'form_type' => '2',
                'group_id' => null,
                'wf_type_id' => 5,
                'custom_field_id' => 48,
                'sort' => 66,
                'active' => '1',
                'created_at' => '2025-12-30 10:29:55',
                'updated_at' => '2025-12-30 10:29:55',
                'validation_type_id' => 1,
                'enable' => 1,
                'status_id' => 239,
            ],
            [
                'form_type' => '2',
                'group_id' => null,
                'wf_type_id' => 5,
                'custom_field_id' => 67,
                'sort' => 66,
                'active' => '1',
                'created_at' => '2025-12-30 10:29:55',
                'updated_at' => '2025-12-30 10:29:55',
                'validation_type_id' => null,
                'enable' => 0,
                'status_id' => 239,
            ],
            [
                'form_type' => '2',
                'group_id' => null,
                'wf_type_id' => 5,
                'custom_field_id' => 8,
                'sort' => 77,
                'active' => '1',
                'created_at' => '2025-12-30 10:38:40',
                'updated_at' => '2025-12-30 10:38:40',
                'validation_type_id' => null,
                'enable' => 1,
                'status_id' => 240,
            ],
            [
                'form_type' => '2',
                'group_id' => null,
                'wf_type_id' => 5,
                'custom_field_id' => 9,
                'sort' => 99,
                'active' => '1',
                'created_at' => '2025-12-30 10:38:40',
                'updated_at' => '2025-12-30 10:38:40',
                'validation_type_id' => null,
                'enable' => 1,
                'status_id' => 240,
            ],
            [
                'form_type' => '2',
                'group_id' => null,
                'wf_type_id' => 5,
                'custom_field_id' => 48,
                'sort' => 88,
                'active' => '1',
                'created_at' => '2025-12-30 10:38:40',
                'updated_at' => '2025-12-30 10:38:40',
                'validation_type_id' => null,
                'enable' => 0,
                'status_id' => 240,
            ],
            [
                'form_type' => '2',
                'group_id' => null,
                'wf_type_id' => 5,
                'custom_field_id' => 67,
                'sort' => 77,
                'active' => '1',
                'created_at' => '2025-12-30 10:38:40',
                'updated_at' => '2025-12-30 10:38:40',
                'validation_type_id' => null,
                'enable' => 0,
                'status_id' => 240,
            ],
            [
                'form_type' => '2',
                'group_id' => null,
                'wf_type_id' => 5,
                'custom_field_id' => 8,
                'sort' => 55,
                'active' => '1',
                'created_at' => '2025-12-30 10:45:50',
                'updated_at' => '2025-12-30 10:45:50',
                'validation_type_id' => null,
                'enable' => 1,
                'status_id' => 241,
            ],
            [
                'form_type' => '2',
                'group_id' => null,
                'wf_type_id' => 5,
                'custom_field_id' => 9,
                'sort' => 77,
                'active' => '1',
                'created_at' => '2025-12-30 10:45:50',
                'updated_at' => '2025-12-30 10:45:50',
                'validation_type_id' => null,
                'enable' => 1,
                'status_id' => 241,
            ],
            [
                'form_type' => '2',
                'group_id' => null,
                'wf_type_id' => 5,
                'custom_field_id' => 48,
                'sort' => 88,
                'active' => '1',
                'created_at' => '2025-12-30 10:45:50',
                'updated_at' => '2025-12-30 10:45:50',
                'validation_type_id' => null,
                'enable' => 0,
                'status_id' => 241,
            ],
            [
                'form_type' => '2',
                'group_id' => null,
                'wf_type_id' => 5,
                'custom_field_id' => 67,
                'sort' => 77,
                'active' => '1',
                'created_at' => '2025-12-30 10:45:50',
                'updated_at' => '2025-12-30 10:45:50',
                'validation_type_id' => null,
                'enable' => 0,
                'status_id' => 241,
            ],
            [
                'form_type' => '1',
                'group_id' => 65,
                'wf_type_id' => null,
                'custom_field_id' => 108,
                'sort' => 100,
                'active' => '1',
                'created_at' => '2025-12-30 11:07:33',
                'updated_at' => '2025-12-30 11:07:33',
                'validation_type_id' => null,
                'enable' => 1,
                'status_id' => null,
            ],
            [
                'form_type' => '2',
                'group_id' => 65,
                'wf_type_id' => null,
                'custom_field_id' => 108,
                'sort' => 100,
                'active' => '1',
                'created_at' => '2025-12-30 11:07:33',
                'updated_at' => '2025-12-30 11:07:33',
                'validation_type_id' => null,
                'enable' => 1,
                'status_id' => null,
            ],
            [
                'form_type' => '3',
                'group_id' => 65,
                'wf_type_id' => null,
                'custom_field_id' => 108,
                'sort' => 100,
                'active' => '1',
                'created_at' => '2025-12-30 11:07:33',
                'updated_at' => '2025-12-30 11:07:33',
                'validation_type_id' => null,
                'enable' => 1,
                'status_id' => null,
            ],
            [
                'form_type' => '2',
                'group_id' => null,
                'wf_type_id' => 5,
                'custom_field_id' => 8,
                'sort' => 99,
                'active' => '1',
                'created_at' => '2025-12-30 15:10:18',
                'updated_at' => '2025-12-30 15:10:18',
                'validation_type_id' => null,
                'enable' => 1,
                'status_id' => 245,
            ],
            [
                'form_type' => '2',
                'group_id' => null,
                'wf_type_id' => 5,
                'custom_field_id' => 9,
                'sort' => 77,
                'active' => '1',
                'created_at' => '2025-12-30 15:10:18',
                'updated_at' => '2025-12-30 15:10:18',
                'validation_type_id' => null,
                'enable' => 1,
                'status_id' => 245,
            ],
            [
                'form_type' => '2',
                'group_id' => null,
                'wf_type_id' => 5,
                'custom_field_id' => 48,
                'sort' => 66,
                'active' => '1',
                'created_at' => '2025-12-30 15:10:18',
                'updated_at' => '2025-12-30 15:10:18',
                'validation_type_id' => null,
                'enable' => 0,
                'status_id' => 245,
            ],
            [
                'form_type' => '2',
                'group_id' => null,
                'wf_type_id' => 5,
                'custom_field_id' => 67,
                'sort' => 77,
                'active' => '1',
                'created_at' => '2025-12-30 15:10:18',
                'updated_at' => '2025-12-30 15:10:18',
                'validation_type_id' => null,
                'enable' => 0,
                'status_id' => 245,
            ],
            [
                'form_type' => '2',
                'group_id' => null,
                'wf_type_id' => 5,
                'custom_field_id' => 108,
                'sort' => 88,
                'active' => '1',
                'created_at' => '2025-12-30 15:10:18',
                'updated_at' => '2025-12-30 15:10:18',
                'validation_type_id' => null,
                'enable' => 0,
                'status_id' => 245,
            ],
            [
                'form_type' => '2',
                'group_id' => null,
                'wf_type_id' => 5,
                'custom_field_id' => 8,
                'sort' => 88,
                'active' => '1',
                'created_at' => '2025-12-30 15:14:03',
                'updated_at' => '2025-12-30 15:14:03',
                'validation_type_id' => null,
                'enable' => 1,
                'status_id' => 252,
            ],
            [
                'form_type' => '2',
                'group_id' => null,
                'wf_type_id' => 5,
                'custom_field_id' => 9,
                'sort' => 55,
                'active' => '1',
                'created_at' => '2025-12-30 15:14:03',
                'updated_at' => '2025-12-30 15:14:03',
                'validation_type_id' => null,
                'enable' => 1,
                'status_id' => 252,
            ],
            [
                'form_type' => '2',
                'group_id' => null,
                'wf_type_id' => 5,
                'custom_field_id' => 48,
                'sort' => 77,
                'active' => '1',
                'created_at' => '2025-12-30 15:14:03',
                'updated_at' => '2025-12-30 15:14:03',
                'validation_type_id' => null,
                'enable' => 0,
                'status_id' => 252,
            ],
            [
                'form_type' => '2',
                'group_id' => null,
                'wf_type_id' => 5,
                'custom_field_id' => 67,
                'sort' => 66,
                'active' => '1',
                'created_at' => '2025-12-30 15:14:03',
                'updated_at' => '2025-12-30 15:14:03',
                'validation_type_id' => null,
                'enable' => 0,
                'status_id' => 252,
            ],
            [
                'form_type' => '2',
                'group_id' => null,
                'wf_type_id' => 5,
                'custom_field_id' => 108,
                'sort' => 77,
                'active' => '1',
                'created_at' => '2025-12-30 15:14:03',
                'updated_at' => '2025-12-30 15:14:03',
                'validation_type_id' => null,
                'enable' => 0,
                'status_id' => 252,
            ],
            [
                'form_type' => '2',
                'group_id' => null,
                'wf_type_id' => 5,
                'custom_field_id' => 8,
                'sort' => 77,
                'active' => '1',
                'created_at' => '2025-12-30 15:25:19',
                'updated_at' => '2025-12-30 15:25:19',
                'validation_type_id' => null,
                'enable' => 1,
                'status_id' => 250,
            ],
            [
                'form_type' => '2',
                'group_id' => null,
                'wf_type_id' => 5,
                'custom_field_id' => 9,
                'sort' => 99,
                'active' => '1',
                'created_at' => '2025-12-30 15:25:19',
                'updated_at' => '2025-12-30 15:25:19',
                'validation_type_id' => null,
                'enable' => 1,
                'status_id' => 250,
            ],
            [
                'form_type' => '2',
                'group_id' => null,
                'wf_type_id' => 5,
                'custom_field_id' => 48,
                'sort' => 77,
                'active' => '1',
                'created_at' => '2025-12-30 15:25:19',
                'updated_at' => '2025-12-30 15:25:19',
                'validation_type_id' => null,
                'enable' => 0,
                'status_id' => 250,
            ],
            [
                'form_type' => '2',
                'group_id' => null,
                'wf_type_id' => 5,
                'custom_field_id' => 67,
                'sort' => 88,
                'active' => '1',
                'created_at' => '2025-12-30 15:25:19',
                'updated_at' => '2025-12-30 15:25:19',
                'validation_type_id' => null,
                'enable' => 0,
                'status_id' => 250,
            ],
            [
                'form_type' => '2',
                'group_id' => null,
                'wf_type_id' => 5,
                'custom_field_id' => 108,
                'sort' => 66,
                'active' => '1',
                'created_at' => '2025-12-30 15:25:19',
                'updated_at' => '2025-12-30 15:25:19',
                'validation_type_id' => null,
                'enable' => 0,
                'status_id' => 250,
            ],
            [
                'form_type' => '2',
                'group_id' => null,
                'wf_type_id' => 5,
                'custom_field_id' => 8,
                'sort' => 88,
                'active' => '1',
                'created_at' => '2025-12-30 15:38:07',
                'updated_at' => '2025-12-30 15:38:07',
                'validation_type_id' => null,
                'enable' => 1,
                'status_id' => 266,
            ],
            [
                'form_type' => '2',
                'group_id' => null,
                'wf_type_id' => 5,
                'custom_field_id' => 9,
                'sort' => 66,
                'active' => '1',
                'created_at' => '2025-12-30 15:38:07',
                'updated_at' => '2025-12-30 15:38:07',
                'validation_type_id' => null,
                'enable' => 1,
                'status_id' => 266,
            ],
            [
                'form_type' => '2',
                'group_id' => null,
                'wf_type_id' => 5,
                'custom_field_id' => 48,
                'sort' => 88,
                'active' => '1',
                'created_at' => '2025-12-30 15:38:07',
                'updated_at' => '2025-12-30 15:38:07',
                'validation_type_id' => null,
                'enable' => 0,
                'status_id' => 266,
            ],
            [
                'form_type' => '2',
                'group_id' => null,
                'wf_type_id' => 5,
                'custom_field_id' => 67,
                'sort' => 77,
                'active' => '1',
                'created_at' => '2025-12-30 15:38:07',
                'updated_at' => '2025-12-30 15:38:07',
                'validation_type_id' => null,
                'enable' => 0,
                'status_id' => 266,
            ],
            [
                'form_type' => '2',
                'group_id' => null,
                'wf_type_id' => 5,
                'custom_field_id' => 108,
                'sort' => 77,
                'active' => '1',
                'created_at' => '2025-12-30 15:38:07',
                'updated_at' => '2025-12-30 15:38:07',
                'validation_type_id' => null,
                'enable' => 0,
                'status_id' => 266,
            ],
            [
                'form_type' => '2',
                'group_id' => null,
                'wf_type_id' => 5,
                'custom_field_id' => 8,
                'sort' => 60,
                'active' => '1',
                'created_at' => '2025-12-30 15:59:47',
                'updated_at' => '2025-12-30 15:59:47',
                'validation_type_id' => null,
                'enable' => 1,
                'status_id' => 253,
            ],
            [
                'form_type' => '2',
                'group_id' => null,
                'wf_type_id' => 5,
                'custom_field_id' => 9,
                'sort' => 85,
                'active' => '1',
                'created_at' => '2025-12-30 15:59:47',
                'updated_at' => '2025-12-30 15:59:47',
                'validation_type_id' => null,
                'enable' => 1,
                'status_id' => 253,
            ],
            [
                'form_type' => '2',
                'group_id' => null,
                'wf_type_id' => 5,
                'custom_field_id' => 48,
                'sort' => 80,
                'active' => '1',
                'created_at' => '2025-12-30 15:59:47',
                'updated_at' => '2025-12-30 15:59:47',
                'validation_type_id' => null,
                'enable' => 0,
                'status_id' => 253,
            ],
            [
                'form_type' => '2',
                'group_id' => null,
                'wf_type_id' => 5,
                'custom_field_id' => 67,
                'sort' => 77,
                'active' => '1',
                'created_at' => '2025-12-30 15:59:47',
                'updated_at' => '2025-12-30 15:59:47',
                'validation_type_id' => null,
                'enable' => 1,
                'status_id' => 253,
            ],
            [
                'form_type' => '2',
                'group_id' => null,
                'wf_type_id' => 5,
                'custom_field_id' => 69,
                'sort' => 88,
                'active' => '1',
                'created_at' => '2025-12-30 15:59:47',
                'updated_at' => '2025-12-30 15:59:47',
                'validation_type_id' => null,
                'enable' => 1,
                'status_id' => 253,
            ],
            [
                'form_type' => '2',
                'group_id' => null,
                'wf_type_id' => 5,
                'custom_field_id' => 108,
                'sort' => 99,
                'active' => '1',
                'created_at' => '2025-12-30 15:59:47',
                'updated_at' => '2025-12-30 15:59:47',
                'validation_type_id' => null,
                'enable' => 0,
                'status_id' => 253,
            ],
            [
                'form_type' => '2',
                'group_id' => null,
                'wf_type_id' => 5,
                'custom_field_id' => 8,
                'sort' => 55,
                'active' => '1',
                'created_at' => '2025-12-30 16:03:48',
                'updated_at' => '2025-12-30 16:03:48',
                'validation_type_id' => null,
                'enable' => 1,
                'status_id' => 255,
            ],
            [
                'form_type' => '2',
                'group_id' => null,
                'wf_type_id' => 5,
                'custom_field_id' => 9,
                'sort' => 77,
                'active' => '1',
                'created_at' => '2025-12-30 16:03:48',
                'updated_at' => '2025-12-30 16:03:48',
                'validation_type_id' => null,
                'enable' => 1,
                'status_id' => 255,
            ],
            [
                'form_type' => '2',
                'group_id' => null,
                'wf_type_id' => 5,
                'custom_field_id' => 48,
                'sort' => 66,
                'active' => '1',
                'created_at' => '2025-12-30 16:03:48',
                'updated_at' => '2025-12-30 16:03:48',
                'validation_type_id' => null,
                'enable' => 0,
                'status_id' => 255,
            ],
            [
                'form_type' => '2',
                'group_id' => null,
                'wf_type_id' => 5,
                'custom_field_id' => 67,
                'sort' => 77,
                'active' => '1',
                'created_at' => '2025-12-30 16:03:48',
                'updated_at' => '2025-12-30 16:03:48',
                'validation_type_id' => null,
                'enable' => 0,
                'status_id' => 255,
            ],
            [
                'form_type' => '2',
                'group_id' => null,
                'wf_type_id' => 5,
                'custom_field_id' => 69,
                'sort' => 88,
                'active' => '1',
                'created_at' => '2025-12-30 16:03:48',
                'updated_at' => '2025-12-30 16:03:48',
                'validation_type_id' => null,
                'enable' => 1,
                'status_id' => 255,
            ],
            [
                'form_type' => '2',
                'group_id' => null,
                'wf_type_id' => 5,
                'custom_field_id' => 108,
                'sort' => 99,
                'active' => '1',
                'created_at' => '2025-12-30 16:03:48',
                'updated_at' => '2025-12-30 16:03:48',
                'validation_type_id' => null,
                'enable' => 0,
                'status_id' => 255,
            ],
            [
                'form_type' => '2',
                'group_id' => null,
                'wf_type_id' => 5,
                'custom_field_id' => 8,
                'sort' => 99,
                'active' => '1',
                'created_at' => '2025-12-30 21:43:36',
                'updated_at' => '2025-12-30 21:43:36',
                'validation_type_id' => null,
                'enable' => 1,
                'status_id' => 257,
            ],
            [
                'form_type' => '2',
                'group_id' => null,
                'wf_type_id' => 5,
                'custom_field_id' => 9,
                'sort' => 88,
                'active' => '1',
                'created_at' => '2025-12-30 21:43:36',
                'updated_at' => '2025-12-30 21:43:36',
                'validation_type_id' => null,
                'enable' => 1,
                'status_id' => 257,
            ],
            [
                'form_type' => '2',
                'group_id' => null,
                'wf_type_id' => 5,
                'custom_field_id' => 48,
                'sort' => 77,
                'active' => '1',
                'created_at' => '2025-12-30 21:43:36',
                'updated_at' => '2025-12-30 21:43:36',
                'validation_type_id' => null,
                'enable' => 0,
                'status_id' => 257,
            ],
            [
                'form_type' => '2',
                'group_id' => null,
                'wf_type_id' => 5,
                'custom_field_id' => 67,
                'sort' => 44,
                'active' => '1',
                'created_at' => '2025-12-30 21:43:36',
                'updated_at' => '2025-12-30 21:43:36',
                'validation_type_id' => null,
                'enable' => 0,
                'status_id' => 257,
            ],
            [
                'form_type' => '2',
                'group_id' => null,
                'wf_type_id' => 5,
                'custom_field_id' => 69,
                'sort' => 57,
                'active' => '1',
                'created_at' => '2025-12-30 21:43:36',
                'updated_at' => '2025-12-30 21:43:36',
                'validation_type_id' => null,
                'enable' => 0,
                'status_id' => 257,
            ],
            [
                'form_type' => '2',
                'group_id' => null,
                'wf_type_id' => 5,
                'custom_field_id' => 108,
                'sort' => 66,
                'active' => '1',
                'created_at' => '2025-12-30 21:43:36',
                'updated_at' => '2025-12-30 21:43:36',
                'validation_type_id' => null,
                'enable' => 0,
                'status_id' => 257,
            ],
            [
                'form_type' => '2',
                'group_id' => null,
                'wf_type_id' => 5,
                'custom_field_id' => 48,
                'sort' => 33,
                'active' => '1',
                'created_at' => '2025-12-31 00:00:42',
                'updated_at' => '2025-12-31 00:00:42',
                'validation_type_id' => null,
                'enable' => 0,
                'status_id' => 254,
            ],
            [
                'form_type' => '2',
                'group_id' => null,
                'wf_type_id' => 5,
                'custom_field_id' => 67,
                'sort' => 66,
                'active' => '1',
                'created_at' => '2025-12-31 00:00:42',
                'updated_at' => '2025-12-31 00:00:42',
                'validation_type_id' => null,
                'enable' => 0,
                'status_id' => 254,
            ],
            [
                'form_type' => '2',
                'group_id' => null,
                'wf_type_id' => 5,
                'custom_field_id' => 69,
                'sort' => 66,
                'active' => '1',
                'created_at' => '2025-12-31 00:00:42',
                'updated_at' => '2025-12-31 00:00:42',
                'validation_type_id' => null,
                'enable' => 0,
                'status_id' => 254,
            ],
            [
                'form_type' => '2',
                'group_id' => null,
                'wf_type_id' => 5,
                'custom_field_id' => 72,
                'sort' => 88,
                'active' => '1',
                'created_at' => '2025-12-31 00:00:42',
                'updated_at' => '2025-12-31 00:00:42',
                'validation_type_id' => null,
                'enable' => 1,
                'status_id' => 254,
            ],
            [
                'form_type' => '2',
                'group_id' => null,
                'wf_type_id' => 5,
                'custom_field_id' => 82,
                'sort' => 66,
                'active' => '1',
                'created_at' => '2025-12-31 00:00:42',
                'updated_at' => '2025-12-31 00:00:42',
                'validation_type_id' => null,
                'enable' => 1,
                'status_id' => 254,
            ],
            [
                'form_type' => '2',
                'group_id' => null,
                'wf_type_id' => 5,
                'custom_field_id' => 108,
                'sort' => 55,
                'active' => '1',
                'created_at' => '2025-12-31 00:00:42',
                'updated_at' => '2025-12-31 00:00:42',
                'validation_type_id' => null,
                'enable' => 0,
                'status_id' => 254,
            ],
            [
                'form_type' => '2',
                'group_id' => null,
                'wf_type_id' => 5,
                'custom_field_id' => 8,
                'sort' => 99,
                'active' => '1',
                'created_at' => '2025-12-31 14:22:21',
                'updated_at' => '2025-12-31 14:22:21',
                'validation_type_id' => null,
                'enable' => 1,
                'status_id' => 258,
            ],
            [
                'form_type' => '2',
                'group_id' => null,
                'wf_type_id' => 5,
                'custom_field_id' => 9,
                'sort' => 88,
                'active' => '1',
                'created_at' => '2025-12-31 14:22:21',
                'updated_at' => '2025-12-31 14:22:21',
                'validation_type_id' => null,
                'enable' => 1,
                'status_id' => 258,
            ],
            [
                'form_type' => '2',
                'group_id' => null,
                'wf_type_id' => 5,
                'custom_field_id' => 48,
                'sort' => 44,
                'active' => '1',
                'created_at' => '2025-12-31 14:22:21',
                'updated_at' => '2025-12-31 14:22:21',
                'validation_type_id' => null,
                'enable' => 0,
                'status_id' => 258,
            ],
            [
                'form_type' => '2',
                'group_id' => null,
                'wf_type_id' => 5,
                'custom_field_id' => 67,
                'sort' => 66,
                'active' => '1',
                'created_at' => '2025-12-31 14:22:21',
                'updated_at' => '2025-12-31 14:22:21',
                'validation_type_id' => null,
                'enable' => 0,
                'status_id' => 258,
            ],
            [
                'form_type' => '2',
                'group_id' => null,
                'wf_type_id' => 5,
                'custom_field_id' => 69,
                'sort' => 66,
                'active' => '1',
                'created_at' => '2025-12-31 14:22:21',
                'updated_at' => '2025-12-31 14:22:21',
                'validation_type_id' => null,
                'enable' => 0,
                'status_id' => 258,
            ],
            [
                'form_type' => '2',
                'group_id' => null,
                'wf_type_id' => 5,
                'custom_field_id' => 94,
                'sort' => 55,
                'active' => '1',
                'created_at' => '2025-12-31 14:22:21',
                'updated_at' => '2025-12-31 14:22:21',
                'validation_type_id' => 1,
                'enable' => 1,
                'status_id' => 258,
            ],
            [
                'form_type' => '2',
                'group_id' => null,
                'wf_type_id' => 5,
                'custom_field_id' => 108,
                'sort' => 77,
                'active' => '1',
                'created_at' => '2025-12-31 14:22:21',
                'updated_at' => '2025-12-31 14:22:21',
                'validation_type_id' => null,
                'enable' => 0,
                'status_id' => 258,
            ],
            [
                'form_type' => '2',
                'group_id' => null,
                'wf_type_id' => 5,
                'custom_field_id' => 8,
                'sort' => 66,
                'active' => '1',
                'created_at' => '2025-12-31 14:29:51',
                'updated_at' => '2025-12-31 14:29:51',
                'validation_type_id' => null,
                'enable' => 1,
                'status_id' => 259,
            ],
            [
                'form_type' => '2',
                'group_id' => null,
                'wf_type_id' => 5,
                'custom_field_id' => 9,
                'sort' => 77,
                'active' => '1',
                'created_at' => '2025-12-31 14:29:51',
                'updated_at' => '2025-12-31 14:29:51',
                'validation_type_id' => null,
                'enable' => 1,
                'status_id' => 259,
            ],
            [
                'form_type' => '2',
                'group_id' => null,
                'wf_type_id' => 5,
                'custom_field_id' => 48,
                'sort' => null,
                'active' => '1',
                'created_at' => '2025-12-31 14:29:51',
                'updated_at' => '2025-12-31 14:29:51',
                'validation_type_id' => null,
                'enable' => 1,
                'status_id' => 259,
            ],
            [
                'form_type' => '2',
                'group_id' => null,
                'wf_type_id' => 5,
                'custom_field_id' => 67,
                'sort' => 88,
                'active' => '1',
                'created_at' => '2025-12-31 14:29:51',
                'updated_at' => '2025-12-31 14:29:51',
                'validation_type_id' => null,
                'enable' => 0,
                'status_id' => 259,
            ],
            [
                'form_type' => '2',
                'group_id' => null,
                'wf_type_id' => 5,
                'custom_field_id' => 69,
                'sort' => 66,
                'active' => '1',
                'created_at' => '2025-12-31 14:29:51',
                'updated_at' => '2025-12-31 14:29:51',
                'validation_type_id' => null,
                'enable' => 0,
                'status_id' => 259,
            ],
            [
                'form_type' => '2',
                'group_id' => null,
                'wf_type_id' => 5,
                'custom_field_id' => 94,
                'sort' => 66,
                'active' => '1',
                'created_at' => '2025-12-31 14:29:51',
                'updated_at' => '2025-12-31 14:29:51',
                'validation_type_id' => 1,
                'enable' => 1,
                'status_id' => 259,
            ],
            [
                'form_type' => '2',
                'group_id' => null,
                'wf_type_id' => 5,
                'custom_field_id' => 108,
                'sort' => 88,
                'active' => '1',
                'created_at' => '2025-12-31 14:29:51',
                'updated_at' => '2025-12-31 14:29:51',
                'validation_type_id' => null,
                'enable' => 0,
                'status_id' => 259,
            ],
            [
                'form_type' => '2',
                'group_id' => null,
                'wf_type_id' => 5,
                'custom_field_id' => 8,
                'sort' => 77,
                'active' => '1',
                'created_at' => '2025-12-31 17:16:51',
                'updated_at' => '2025-12-31 17:16:51',
                'validation_type_id' => null,
                'enable' => 1,
                'status_id' => 261,
            ],
            [
                'form_type' => '2',
                'group_id' => null,
                'wf_type_id' => 5,
                'custom_field_id' => 9,
                'sort' => 55,
                'active' => '1',
                'created_at' => '2025-12-31 17:16:51',
                'updated_at' => '2025-12-31 17:16:51',
                'validation_type_id' => null,
                'enable' => 1,
                'status_id' => 261,
            ],
            [
                'form_type' => '2',
                'group_id' => null,
                'wf_type_id' => 5,
                'custom_field_id' => 48,
                'sort' => 44,
                'active' => '1',
                'created_at' => '2025-12-31 17:16:51',
                'updated_at' => '2025-12-31 17:16:51',
                'validation_type_id' => null,
                'enable' => 0,
                'status_id' => 261,
            ],
            [
                'form_type' => '2',
                'group_id' => null,
                'wf_type_id' => 5,
                'custom_field_id' => 67,
                'sort' => 88,
                'active' => '1',
                'created_at' => '2025-12-31 17:16:51',
                'updated_at' => '2025-12-31 17:16:51',
                'validation_type_id' => null,
                'enable' => 0,
                'status_id' => 261,
            ],
            [
                'form_type' => '2',
                'group_id' => null,
                'wf_type_id' => 5,
                'custom_field_id' => 69,
                'sort' => 77,
                'active' => '1',
                'created_at' => '2025-12-31 17:16:51',
                'updated_at' => '2025-12-31 17:16:51',
                'validation_type_id' => null,
                'enable' => 0,
                'status_id' => 261,
            ],
            [
                'form_type' => '2',
                'group_id' => null,
                'wf_type_id' => 5,
                'custom_field_id' => 94,
                'sort' => 77,
                'active' => '1',
                'created_at' => '2025-12-31 17:16:51',
                'updated_at' => '2025-12-31 17:16:51',
                'validation_type_id' => null,
                'enable' => 0,
                'status_id' => 261,
            ],
            [
                'form_type' => '2',
                'group_id' => null,
                'wf_type_id' => 5,
                'custom_field_id' => 108,
                'sort' => 66,
                'active' => '1',
                'created_at' => '2025-12-31 17:16:51',
                'updated_at' => '2025-12-31 17:16:51',
                'validation_type_id' => null,
                'enable' => 0,
                'status_id' => 261,
            ],
            [
                'form_type' => '2',
                'group_id' => null,
                'wf_type_id' => 5,
                'custom_field_id' => 8,
                'sort' => 88,
                'active' => '1',
                'created_at' => '2025-12-31 17:58:13',
                'updated_at' => '2025-12-31 17:58:13',
                'validation_type_id' => null,
                'enable' => 1,
                'status_id' => 263,
            ],
            [
                'form_type' => '2',
                'group_id' => null,
                'wf_type_id' => 5,
                'custom_field_id' => 9,
                'sort' => 77,
                'active' => '1',
                'created_at' => '2025-12-31 17:58:13',
                'updated_at' => '2025-12-31 17:58:13',
                'validation_type_id' => null,
                'enable' => 1,
                'status_id' => 263,
            ],
            [
                'form_type' => '2',
                'group_id' => null,
                'wf_type_id' => 5,
                'custom_field_id' => 48,
                'sort' => 55,
                'active' => '1',
                'created_at' => '2025-12-31 17:58:13',
                'updated_at' => '2025-12-31 17:58:13',
                'validation_type_id' => null,
                'enable' => 0,
                'status_id' => 263,
            ],
            [
                'form_type' => '2',
                'group_id' => null,
                'wf_type_id' => 5,
                'custom_field_id' => 67,
                'sort' => 66,
                'active' => '1',
                'created_at' => '2025-12-31 17:58:13',
                'updated_at' => '2025-12-31 17:58:13',
                'validation_type_id' => null,
                'enable' => 0,
                'status_id' => 263,
            ],
            [
                'form_type' => '2',
                'group_id' => null,
                'wf_type_id' => 5,
                'custom_field_id' => 69,
                'sort' => 77,
                'active' => '1',
                'created_at' => '2025-12-31 17:58:13',
                'updated_at' => '2025-12-31 17:58:13',
                'validation_type_id' => null,
                'enable' => 0,
                'status_id' => 263,
            ],
            [
                'form_type' => '2',
                'group_id' => null,
                'wf_type_id' => 5,
                'custom_field_id' => 94,
                'sort' => 88,
                'active' => '1',
                'created_at' => '2025-12-31 17:58:13',
                'updated_at' => '2025-12-31 17:58:13',
                'validation_type_id' => null,
                'enable' => 0,
                'status_id' => 263,
            ],
            [
                'form_type' => '2',
                'group_id' => null,
                'wf_type_id' => 5,
                'custom_field_id' => 108,
                'sort' => 99,
                'active' => '1',
                'created_at' => '2025-12-31 17:58:13',
                'updated_at' => '2025-12-31 17:58:13',
                'validation_type_id' => null,
                'enable' => 0,
                'status_id' => 263,
            ],
            [
                'form_type' => '2',
                'group_id' => null,
                'wf_type_id' => 5,
                'custom_field_id' => 48,
                'sort' => 66,
                'active' => '1',
                'created_at' => '2025-12-31 18:51:49',
                'updated_at' => '2025-12-31 18:51:49',
                'validation_type_id' => null,
                'enable' => 1,
                'status_id' => 262,
            ],
            [
                'form_type' => '2',
                'group_id' => null,
                'wf_type_id' => 5,
                'custom_field_id' => 67,
                'sort' => 55,
                'active' => '1',
                'created_at' => '2025-12-31 18:51:49',
                'updated_at' => '2025-12-31 18:51:49',
                'validation_type_id' => null,
                'enable' => 0,
                'status_id' => 262,
            ],
            [
                'form_type' => '2',
                'group_id' => null,
                'wf_type_id' => 5,
                'custom_field_id' => 69,
                'sort' => 66,
                'active' => '1',
                'created_at' => '2025-12-31 18:51:49',
                'updated_at' => '2025-12-31 18:51:49',
                'validation_type_id' => null,
                'enable' => 0,
                'status_id' => 262,
            ],
            [
                'form_type' => '2',
                'group_id' => null,
                'wf_type_id' => 5,
                'custom_field_id' => 94,
                'sort' => 88,
                'active' => '1',
                'created_at' => '2025-12-31 18:51:49',
                'updated_at' => '2025-12-31 18:51:49',
                'validation_type_id' => null,
                'enable' => 0,
                'status_id' => 262,
            ],
            [
                'form_type' => '2',
                'group_id' => null,
                'wf_type_id' => 5,
                'custom_field_id' => 108,
                'sort' => 77,
                'active' => '1',
                'created_at' => '2025-12-31 18:51:49',
                'updated_at' => '2025-12-31 18:51:49',
                'validation_type_id' => null,
                'enable' => 0,
                'status_id' => 262,
            ],
            [
                'form_type' => '2',
                'group_id' => null,
                'wf_type_id' => 5,
                'custom_field_id' => 109,
                'sort' => 99,
                'active' => '1',
                'created_at' => '2025-12-31 18:51:49',
                'updated_at' => '2025-12-31 18:51:49',
                'validation_type_id' => null,
                'enable' => 1,
                'status_id' => 262,
            ],
            [
                'form_type' => '2',
                'group_id' => null,
                'wf_type_id' => 5,
                'custom_field_id' => 8,
                'sort' => 99,
                'active' => '1',
                'created_at' => '2025-12-31 20:25:24',
                'updated_at' => '2025-12-31 20:25:24',
                'validation_type_id' => null,
                'enable' => 1,
                'status_id' => 260,
            ],
            [
                'form_type' => '2',
                'group_id' => null,
                'wf_type_id' => 5,
                'custom_field_id' => 9,
                'sort' => 66,
                'active' => '1',
                'created_at' => '2025-12-31 20:25:24',
                'updated_at' => '2025-12-31 20:25:24',
                'validation_type_id' => null,
                'enable' => 1,
                'status_id' => 260,
            ],
            [
                'form_type' => '2',
                'group_id' => null,
                'wf_type_id' => 5,
                'custom_field_id' => 48,
                'sort' => 66,
                'active' => '1',
                'created_at' => '2025-12-31 20:25:24',
                'updated_at' => '2025-12-31 20:25:24',
                'validation_type_id' => null,
                'enable' => 0,
                'status_id' => 260,
            ],
            [
                'form_type' => '2',
                'group_id' => null,
                'wf_type_id' => 5,
                'custom_field_id' => 67,
                'sort' => 66,
                'active' => '1',
                'created_at' => '2025-12-31 20:25:24',
                'updated_at' => '2025-12-31 20:25:24',
                'validation_type_id' => null,
                'enable' => 0,
                'status_id' => 260,
            ],
            [
                'form_type' => '2',
                'group_id' => null,
                'wf_type_id' => 5,
                'custom_field_id' => 69,
                'sort' => 55,
                'active' => '1',
                'created_at' => '2025-12-31 20:25:24',
                'updated_at' => '2025-12-31 20:25:24',
                'validation_type_id' => null,
                'enable' => 0,
                'status_id' => 260,
            ],
            [
                'form_type' => '2',
                'group_id' => null,
                'wf_type_id' => 5,
                'custom_field_id' => 94,
                'sort' => 66,
                'active' => '1',
                'created_at' => '2025-12-31 20:25:24',
                'updated_at' => '2025-12-31 20:25:24',
                'validation_type_id' => null,
                'enable' => 1,
                'status_id' => 260,
            ],
            [
                'form_type' => '2',
                'group_id' => null,
                'wf_type_id' => 5,
                'custom_field_id' => 108,
                'sort' => 88,
                'active' => '1',
                'created_at' => '2025-12-31 20:25:24',
                'updated_at' => '2025-12-31 20:25:24',
                'validation_type_id' => null,
                'enable' => 0,
                'status_id' => 260,
            ],
            [
                'form_type' => '2',
                'group_id' => null,
                'wf_type_id' => 5,
                'custom_field_id' => 8,
                'sort' => 77,
                'active' => '1',
                'created_at' => '2025-12-31 20:52:08',
                'updated_at' => '2025-12-31 20:52:08',
                'validation_type_id' => null,
                'enable' => 1,
                'status_id' => 238,
            ],
            [
                'form_type' => '2',
                'group_id' => null,
                'wf_type_id' => 5,
                'custom_field_id' => 9,
                'sort' => 88,
                'active' => '1',
                'created_at' => '2025-12-31 20:52:08',
                'updated_at' => '2025-12-31 20:52:08',
                'validation_type_id' => null,
                'enable' => 1,
                'status_id' => 238,
            ],
            [
                'form_type' => '2',
                'group_id' => null,
                'wf_type_id' => 5,
                'custom_field_id' => 67,
                'sort' => 77,
                'active' => '1',
                'created_at' => '2025-12-31 20:52:08',
                'updated_at' => '2025-12-31 20:52:08',
                'validation_type_id' => null,
                'enable' => 0,
                'status_id' => 238,
            ],
            [
                'form_type' => '2',
                'group_id' => null,
                'wf_type_id' => 5,
                'custom_field_id' => 105,
                'sort' => 88,
                'active' => '1',
                'created_at' => '2025-12-31 20:52:08',
                'updated_at' => '2025-12-31 20:52:08',
                'validation_type_id' => null,
                'enable' => 0,
                'status_id' => 238,
            ],
            [
                'form_type' => '2',
                'group_id' => null,
                'wf_type_id' => 5,
                'custom_field_id' => 8,
                'sort' => 66,
                'active' => '1',
                'created_at' => '2025-12-31 20:55:48',
                'updated_at' => '2025-12-31 20:55:48',
                'validation_type_id' => null,
                'enable' => 1,
                'status_id' => 242,
            ],
            [
                'form_type' => '2',
                'group_id' => null,
                'wf_type_id' => 5,
                'custom_field_id' => 9,
                'sort' => 77,
                'active' => '1',
                'created_at' => '2025-12-31 20:55:48',
                'updated_at' => '2025-12-31 20:55:48',
                'validation_type_id' => null,
                'enable' => 1,
                'status_id' => 242,
            ],
            [
                'form_type' => '2',
                'group_id' => null,
                'wf_type_id' => 5,
                'custom_field_id' => 67,
                'sort' => 44,
                'active' => '1',
                'created_at' => '2025-12-31 20:55:48',
                'updated_at' => '2025-12-31 20:55:48',
                'validation_type_id' => null,
                'enable' => 0,
                'status_id' => 242,
            ],
            [
                'form_type' => '2',
                'group_id' => null,
                'wf_type_id' => 5,
                'custom_field_id' => 105,
                'sort' => 33,
                'active' => '1',
                'created_at' => '2025-12-31 20:55:48',
                'updated_at' => '2025-12-31 20:55:48',
                'validation_type_id' => null,
                'enable' => 0,
                'status_id' => 242,
            ],
            [
                'form_type' => '2',
                'group_id' => null,
                'wf_type_id' => 5,
                'custom_field_id' => 8,
                'sort' => 77,
                'active' => '1',
                'created_at' => '2025-12-31 20:58:57',
                'updated_at' => '2025-12-31 20:58:57',
                'validation_type_id' => null,
                'enable' => 1,
                'status_id' => 243,
            ],
            [
                'form_type' => '2',
                'group_id' => null,
                'wf_type_id' => 5,
                'custom_field_id' => 9,
                'sort' => 88,
                'active' => '1',
                'created_at' => '2025-12-31 20:58:58',
                'updated_at' => '2025-12-31 20:58:58',
                'validation_type_id' => null,
                'enable' => 1,
                'status_id' => 243,
            ],
            [
                'form_type' => '2',
                'group_id' => null,
                'wf_type_id' => 5,
                'custom_field_id' => 67,
                'sort' => 77,
                'active' => '1',
                'created_at' => '2025-12-31 20:58:58',
                'updated_at' => '2025-12-31 20:58:58',
                'validation_type_id' => null,
                'enable' => 0,
                'status_id' => 243,
            ],
            [
                'form_type' => '2',
                'group_id' => null,
                'wf_type_id' => 5,
                'custom_field_id' => 8,
                'sort' => 55,
                'active' => '1',
                'created_at' => '2025-12-31 21:06:09',
                'updated_at' => '2025-12-31 21:06:09',
                'validation_type_id' => null,
                'enable' => 1,
                'status_id' => 244,
            ],
            [
                'form_type' => '2',
                'group_id' => null,
                'wf_type_id' => 5,
                'custom_field_id' => 9,
                'sort' => 66,
                'active' => '1',
                'created_at' => '2025-12-31 21:06:09',
                'updated_at' => '2025-12-31 21:06:09',
                'validation_type_id' => null,
                'enable' => 1,
                'status_id' => 244,
            ],
            [
                'form_type' => '2',
                'group_id' => null,
                'wf_type_id' => 5,
                'custom_field_id' => 48,
                'sort' => 88,
                'active' => '1',
                'created_at' => '2025-12-31 21:06:09',
                'updated_at' => '2025-12-31 21:06:09',
                'validation_type_id' => null,
                'enable' => 1,
                'status_id' => 244,
            ],
            [
                'form_type' => '2',
                'group_id' => null,
                'wf_type_id' => 5,
                'custom_field_id' => 67,
                'sort' => 66,
                'active' => '1',
                'created_at' => '2025-12-31 21:06:09',
                'updated_at' => '2025-12-31 21:06:09',
                'validation_type_id' => null,
                'enable' => 0,
                'status_id' => 244,
            ],
            [
                'form_type' => '2',
                'group_id' => null,
                'wf_type_id' => 5,
                'custom_field_id' => 108,
                'sort' => 77,
                'active' => '1',
                'created_at' => '2025-12-31 21:06:09',
                'updated_at' => '2025-12-31 21:06:09',
                'validation_type_id' => null,
                'enable' => 1,
                'status_id' => 244,
            ],
            [
                'form_type' => '2',
                'group_id' => null,
                'wf_type_id' => 5,
                'custom_field_id' => 8,
                'sort' => 88,
                'active' => '1',
                'created_at' => '2025-12-31 21:36:42',
                'updated_at' => '2025-12-31 21:36:42',
                'validation_type_id' => null,
                'enable' => 1,
                'status_id' => 246,
            ],
            [
                'form_type' => '2',
                'group_id' => null,
                'wf_type_id' => 5,
                'custom_field_id' => 9,
                'sort' => 99,
                'active' => '1',
                'created_at' => '2025-12-31 21:36:42',
                'updated_at' => '2025-12-31 21:36:42',
                'validation_type_id' => null,
                'enable' => 1,
                'status_id' => 246,
            ],
            [
                'form_type' => '2',
                'group_id' => null,
                'wf_type_id' => 5,
                'custom_field_id' => 48,
                'sort' => 44,
                'active' => '1',
                'created_at' => '2025-12-31 21:36:42',
                'updated_at' => '2025-12-31 21:36:42',
                'validation_type_id' => null,
                'enable' => 0,
                'status_id' => 246,
            ],
            [
                'form_type' => '2',
                'group_id' => null,
                'wf_type_id' => 5,
                'custom_field_id' => 67,
                'sort' => 55,
                'active' => '1',
                'created_at' => '2025-12-31 21:36:42',
                'updated_at' => '2025-12-31 21:36:42',
                'validation_type_id' => null,
                'enable' => 0,
                'status_id' => 246,
            ],
            [
                'form_type' => '2',
                'group_id' => null,
                'wf_type_id' => 5,
                'custom_field_id' => 108,
                'sort' => 77,
                'active' => '1',
                'created_at' => '2025-12-31 21:36:42',
                'updated_at' => '2025-12-31 21:36:42',
                'validation_type_id' => null,
                'enable' => 0,
                'status_id' => 246,
            ],
            [
                'form_type' => '2',
                'group_id' => null,
                'wf_type_id' => 5,
                'custom_field_id' => 110,
                'sort' => 66,
                'active' => '1',
                'created_at' => '2025-12-31 21:36:42',
                'updated_at' => '2025-12-31 21:36:42',
                'validation_type_id' => null,
                'enable' => 1,
                'status_id' => 246,
            ],
            [
                'form_type' => '2',
                'group_id' => null,
                'wf_type_id' => 5,
                'custom_field_id' => 8,
                'sort' => 77,
                'active' => '1',
                'created_at' => '2025-12-31 21:44:31',
                'updated_at' => '2025-12-31 21:44:31',
                'validation_type_id' => null,
                'enable' => 1,
                'status_id' => 247,
            ],
            [
                'form_type' => '2',
                'group_id' => null,
                'wf_type_id' => 5,
                'custom_field_id' => 9,
                'sort' => 88,
                'active' => '1',
                'created_at' => '2025-12-31 21:44:31',
                'updated_at' => '2025-12-31 21:44:31',
                'validation_type_id' => null,
                'enable' => 1,
                'status_id' => 247,
            ],
            [
                'form_type' => '2',
                'group_id' => null,
                'wf_type_id' => 5,
                'custom_field_id' => 48,
                'sort' => 77,
                'active' => '1',
                'created_at' => '2025-12-31 21:44:31',
                'updated_at' => '2025-12-31 21:44:31',
                'validation_type_id' => null,
                'enable' => 0,
                'status_id' => 247,
            ],
            [
                'form_type' => '2',
                'group_id' => null,
                'wf_type_id' => 5,
                'custom_field_id' => 67,
                'sort' => 55,
                'active' => '1',
                'created_at' => '2025-12-31 21:44:31',
                'updated_at' => '2025-12-31 21:44:31',
                'validation_type_id' => null,
                'enable' => 0,
                'status_id' => 247,
            ],
            [
                'form_type' => '2',
                'group_id' => null,
                'wf_type_id' => 5,
                'custom_field_id' => 108,
                'sort' => 77,
                'active' => '1',
                'created_at' => '2025-12-31 21:44:31',
                'updated_at' => '2025-12-31 21:44:31',
                'validation_type_id' => null,
                'enable' => 0,
                'status_id' => 247,
            ],
            [
                'form_type' => '2',
                'group_id' => null,
                'wf_type_id' => 5,
                'custom_field_id' => 110,
                'sort' => 88,
                'active' => '1',
                'created_at' => '2025-12-31 21:44:31',
                'updated_at' => '2025-12-31 21:44:31',
                'validation_type_id' => null,
                'enable' => 0,
                'status_id' => 247,
            ],
            [
                'form_type' => '2',
                'group_id' => null,
                'wf_type_id' => 5,
                'custom_field_id' => 8,
                'sort' => 77,
                'active' => '1',
                'created_at' => '2025-12-31 22:06:32',
                'updated_at' => '2025-12-31 22:06:32',
                'validation_type_id' => null,
                'enable' => 1,
                'status_id' => 248,
            ],
            [
                'form_type' => '2',
                'group_id' => null,
                'wf_type_id' => 5,
                'custom_field_id' => 9,
                'sort' => 66,
                'active' => '1',
                'created_at' => '2025-12-31 22:06:32',
                'updated_at' => '2025-12-31 22:06:32',
                'validation_type_id' => null,
                'enable' => 1,
                'status_id' => 248,
            ],
            [
                'form_type' => '2',
                'group_id' => null,
                'wf_type_id' => 5,
                'custom_field_id' => 48,
                'sort' => 88,
                'active' => '1',
                'created_at' => '2025-12-31 22:06:32',
                'updated_at' => '2025-12-31 22:06:32',
                'validation_type_id' => null,
                'enable' => 0,
                'status_id' => 248,
            ],
            [
                'form_type' => '2',
                'group_id' => null,
                'wf_type_id' => 5,
                'custom_field_id' => 67,
                'sort' => 77,
                'active' => '1',
                'created_at' => '2025-12-31 22:06:32',
                'updated_at' => '2025-12-31 22:06:32',
                'validation_type_id' => null,
                'enable' => 0,
                'status_id' => 248,
            ],
            [
                'form_type' => '2',
                'group_id' => null,
                'wf_type_id' => 5,
                'custom_field_id' => 108,
                'sort' => 99,
                'active' => '1',
                'created_at' => '2025-12-31 22:06:32',
                'updated_at' => '2025-12-31 22:06:32',
                'validation_type_id' => null,
                'enable' => 0,
                'status_id' => 248,
            ],
            [
                'form_type' => '2',
                'group_id' => null,
                'wf_type_id' => 5,
                'custom_field_id' => 48,
                'sort' => 88,
                'active' => '1',
                'created_at' => '2025-12-31 22:16:42',
                'updated_at' => '2025-12-31 22:16:42',
                'validation_type_id' => null,
                'enable' => 0,
                'status_id' => 249,
            ],
            [
                'form_type' => '2',
                'group_id' => null,
                'wf_type_id' => 5,
                'custom_field_id' => 67,
                'sort' => 66,
                'active' => '1',
                'created_at' => '2025-12-31 22:16:42',
                'updated_at' => '2025-12-31 22:16:42',
                'validation_type_id' => null,
                'enable' => 0,
                'status_id' => 249,
            ],
            [
                'form_type' => '2',
                'group_id' => null,
                'wf_type_id' => 5,
                'custom_field_id' => 72,
                'sort' => 66,
                'active' => '1',
                'created_at' => '2025-12-31 22:16:42',
                'updated_at' => '2025-12-31 22:16:42',
                'validation_type_id' => null,
                'enable' => 1,
                'status_id' => 249,
            ],
            [
                'form_type' => '2',
                'group_id' => null,
                'wf_type_id' => 5,
                'custom_field_id' => 82,
                'sort' => 55,
                'active' => '1',
                'created_at' => '2025-12-31 22:16:42',
                'updated_at' => '2025-12-31 22:16:42',
                'validation_type_id' => null,
                'enable' => 1,
                'status_id' => 249,
            ],
            [
                'form_type' => '2',
                'group_id' => null,
                'wf_type_id' => 5,
                'custom_field_id' => 108,
                'sort' => 99,
                'active' => '1',
                'created_at' => '2025-12-31 22:16:42',
                'updated_at' => '2025-12-31 22:16:42',
                'validation_type_id' => null,
                'enable' => 0,
                'status_id' => 249,
            ],
            [
                'form_type' => '2',
                'group_id' => null,
                'wf_type_id' => 5,
                'custom_field_id' => 8,
                'sort' => 55,
                'active' => '1',
                'created_at' => '2025-12-31 22:24:43',
                'updated_at' => '2025-12-31 22:24:43',
                'validation_type_id' => null,
                'enable' => 1,
                'status_id' => 251,
            ],
            [
                'form_type' => '2',
                'group_id' => null,
                'wf_type_id' => 5,
                'custom_field_id' => 9,
                'sort' => 66,
                'active' => '1',
                'created_at' => '2025-12-31 22:24:43',
                'updated_at' => '2025-12-31 22:24:43',
                'validation_type_id' => null,
                'enable' => 1,
                'status_id' => 251,
            ],
            [
                'form_type' => '2',
                'group_id' => null,
                'wf_type_id' => 5,
                'custom_field_id' => 48,
                'sort' => 88,
                'active' => '1',
                'created_at' => '2025-12-31 22:24:43',
                'updated_at' => '2025-12-31 22:24:43',
                'validation_type_id' => null,
                'enable' => 0,
                'status_id' => 251,
            ],
            [
                'form_type' => '2',
                'group_id' => null,
                'wf_type_id' => 5,
                'custom_field_id' => 67,
                'sort' => 66,
                'active' => '1',
                'created_at' => '2025-12-31 22:24:43',
                'updated_at' => '2025-12-31 22:24:43',
                'validation_type_id' => null,
                'enable' => 0,
                'status_id' => 251,
            ],
            [
                'form_type' => '2',
                'group_id' => null,
                'wf_type_id' => 5,
                'custom_field_id' => 108,
                'sort' => 99,
                'active' => '1',
                'created_at' => '2025-12-31 22:24:43',
                'updated_at' => '2025-12-31 22:24:43',
                'validation_type_id' => null,
                'enable' => 0,
                'status_id' => 251,
            ],
            [
                'form_type' => '2',
                'group_id' => null,
                'wf_type_id' => 5,
                'custom_field_id' => 8,
                'sort' => 88,
                'active' => '1',
                'created_at' => '2025-12-31 23:59:26',
                'updated_at' => '2025-12-31 23:59:26',
                'validation_type_id' => null,
                'enable' => 1,
                'status_id' => 256,
            ],
            [
                'form_type' => '2',
                'group_id' => null,
                'wf_type_id' => 5,
                'custom_field_id' => 9,
                'sort' => 99,
                'active' => '1',
                'created_at' => '2025-12-31 23:59:26',
                'updated_at' => '2025-12-31 23:59:26',
                'validation_type_id' => null,
                'enable' => 1,
                'status_id' => 256,
            ],
            [
                'form_type' => '2',
                'group_id' => null,
                'wf_type_id' => 5,
                'custom_field_id' => 48,
                'sort' => 88,
                'active' => '1',
                'created_at' => '2025-12-31 23:59:26',
                'updated_at' => '2025-12-31 23:59:26',
                'validation_type_id' => null,
                'enable' => 0,
                'status_id' => 256,
            ],
            [
                'form_type' => '2',
                'group_id' => null,
                'wf_type_id' => 5,
                'custom_field_id' => 67,
                'sort' => 66,
                'active' => '1',
                'created_at' => '2025-12-31 23:59:26',
                'updated_at' => '2025-12-31 23:59:26',
                'validation_type_id' => null,
                'enable' => 0,
                'status_id' => 256,
            ],
            [
                'form_type' => '2',
                'group_id' => null,
                'wf_type_id' => 5,
                'custom_field_id' => 108,
                'sort' => 99,
                'active' => '1',
                'created_at' => '2025-12-31 23:59:26',
                'updated_at' => '2025-12-31 23:59:26',
                'validation_type_id' => null,
                'enable' => 0,
                'status_id' => 256,
            ],
            [
                'form_type' => '2',
                'group_id' => null,
                'wf_type_id' => 5,
                'custom_field_id' => 8,
                'sort' => 88,
                'active' => '1',
                'created_at' => '2026-01-01 15:40:35',
                'updated_at' => '2026-01-01 15:40:35',
                'validation_type_id' => null,
                'enable' => 1,
                'status_id' => 267,
            ],
            [
                'form_type' => '2',
                'group_id' => null,
                'wf_type_id' => 5,
                'custom_field_id' => 9,
                'sort' => 99,
                'active' => '1',
                'created_at' => '2026-01-01 15:40:35',
                'updated_at' => '2026-01-01 15:40:35',
                'validation_type_id' => null,
                'enable' => 1,
                'status_id' => 267,
            ],
            [
                'form_type' => '2',
                'group_id' => null,
                'wf_type_id' => 5,
                'custom_field_id' => 48,
                'sort' => 77,
                'active' => '1',
                'created_at' => '2026-01-01 15:40:35',
                'updated_at' => '2026-01-01 15:40:35',
                'validation_type_id' => null,
                'enable' => 0,
                'status_id' => 267,
            ],
            [
                'form_type' => '2',
                'group_id' => null,
                'wf_type_id' => 5,
                'custom_field_id' => 67,
                'sort' => 77,
                'active' => '1',
                'created_at' => '2026-01-01 15:40:35',
                'updated_at' => '2026-01-01 15:40:35',
                'validation_type_id' => null,
                'enable' => 1,
                'status_id' => 267,
            ],
            [
                'form_type' => '2',
                'group_id' => null,
                'wf_type_id' => 5,
                'custom_field_id' => 69,
                'sort' => 99,
                'active' => '1',
                'created_at' => '2026-01-01 15:40:35',
                'updated_at' => '2026-01-01 15:40:35',
                'validation_type_id' => null,
                'enable' => 0,
                'status_id' => 267,
            ],
            [
                'form_type' => '2',
                'group_id' => null,
                'wf_type_id' => 5,
                'custom_field_id' => 94,
                'sort' => 88,
                'active' => '1',
                'created_at' => '2026-01-01 15:40:35',
                'updated_at' => '2026-01-01 15:40:35',
                'validation_type_id' => null,
                'enable' => 0,
                'status_id' => 267,
            ],
            [
                'form_type' => '2',
                'group_id' => null,
                'wf_type_id' => 5,
                'custom_field_id' => 108,
                'sort' => 77,
                'active' => '1',
                'created_at' => '2026-01-01 15:40:35',
                'updated_at' => '2026-01-01 15:40:35',
                'validation_type_id' => null,
                'enable' => 0,
                'status_id' => 267,
            ],
            [
                'form_type' => '2',
                'group_id' => null,
                'wf_type_id' => 5,
                'custom_field_id' => 8,
                'sort' => 88,
                'active' => '1',
                'created_at' => '2026-01-01 15:44:43',
                'updated_at' => '2026-01-01 15:44:43',
                'validation_type_id' => null,
                'enable' => 1,
                'status_id' => 268,
            ],
            [
                'form_type' => '2',
                'group_id' => null,
                'wf_type_id' => 5,
                'custom_field_id' => 9,
                'sort' => 99,
                'active' => '1',
                'created_at' => '2026-01-01 15:44:43',
                'updated_at' => '2026-01-01 15:44:43',
                'validation_type_id' => null,
                'enable' => 1,
                'status_id' => 268,
            ],
            [
                'form_type' => '2',
                'group_id' => null,
                'wf_type_id' => 5,
                'custom_field_id' => 48,
                'sort' => 66,
                'active' => '1',
                'created_at' => '2026-01-01 15:44:43',
                'updated_at' => '2026-01-01 15:44:43',
                'validation_type_id' => null,
                'enable' => 0,
                'status_id' => 268,
            ],
            [
                'form_type' => '2',
                'group_id' => null,
                'wf_type_id' => 5,
                'custom_field_id' => 67,
                'sort' => 77,
                'active' => '1',
                'created_at' => '2026-01-01 15:44:43',
                'updated_at' => '2026-01-01 15:44:43',
                'validation_type_id' => null,
                'enable' => 0,
                'status_id' => 268,
            ],
            [
                'form_type' => '2',
                'group_id' => null,
                'wf_type_id' => 5,
                'custom_field_id' => 69,
                'sort' => 55,
                'active' => '1',
                'created_at' => '2026-01-01 15:44:43',
                'updated_at' => '2026-01-01 15:44:43',
                'validation_type_id' => null,
                'enable' => 0,
                'status_id' => 268,
            ],
            [
                'form_type' => '2',
                'group_id' => null,
                'wf_type_id' => 5,
                'custom_field_id' => 94,
                'sort' => 99,
                'active' => '1',
                'created_at' => '2026-01-01 15:44:43',
                'updated_at' => '2026-01-01 15:44:43',
                'validation_type_id' => null,
                'enable' => 0,
                'status_id' => 268,
            ],
            [
                'form_type' => '2',
                'group_id' => null,
                'wf_type_id' => 5,
                'custom_field_id' => 108,
                'sort' => 88,
                'active' => '1',
                'created_at' => '2026-01-01 15:44:43',
                'updated_at' => '2026-01-01 15:44:43',
                'validation_type_id' => null,
                'enable' => 0,
                'status_id' => 268,
            ],
        ];

        // Insert the data
        DB::table('custom_fields_groups_type')->insert($data);
    }
}