<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class NewWorkflowSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $data = [
            [
                'same_time_from' => '0',
                'previous_status_id' => 263,
                'from_status_id' => 260,
                'active' => '1',
                'same_time' => '0',
                'workflow_type' => '0',
                'to_status_label' => null,
                'created_at' => '2025-12-31 20:35:42',
                'updated_at' => '2025-12-31 20:35:42',
                'type_id' => 5,
            ],
            [
                'same_time_from' => '0',
                'previous_status_id' => 249,
                'from_status_id' => 251,
                'active' => '1',
                'same_time' => '0',
                'workflow_type' => '0',
                'to_status_label' => null,
                'created_at' => '2025-12-31 22:33:15',
                'updated_at' => '2025-12-31 22:33:15',
                'type_id' => 5,
            ],
            [
                'same_time_from' => '0',
                'previous_status_id' => 249,
                'from_status_id' => 251,
                'active' => '1',
                'same_time' => '0',
                'workflow_type' => '0',
                'to_status_label' => null,
                'created_at' => '2025-12-31 22:33:19',
                'updated_at' => '2025-12-31 22:33:19',
                'type_id' => 5,
            ],
            [
                'same_time_from' => '0',
                'previous_status_id' => 251,
                'from_status_id' => 248,
                'active' => '1',
                'same_time' => '0',
                'workflow_type' => '0',
                'to_status_label' => 'approved',
                'created_at' => '2025-12-31 22:42:43',
                'updated_at' => '2025-12-31 22:42:43',
                'type_id' => 5,
            ],
            [
                'same_time_from' => '0',
                'previous_status_id' => 251,
                'from_status_id' => 248,
                'active' => '1',
                'same_time' => '0',
                'workflow_type' => '0',
                'to_status_label' => 'Need Update',
                'created_at' => '2025-12-31 22:45:39',
                'updated_at' => '2025-12-31 22:45:39',
                'type_id' => 5,
            ],
            [
                'same_time_from' => '0',
                'previous_status_id' => 248,
                'from_status_id' => 251,
                'active' => '1',
                'same_time' => '0',
                'workflow_type' => '0',
                'to_status_label' => null,
                'created_at' => '2025-12-31 23:44:08',
                'updated_at' => '2025-12-31 23:44:08',
                'type_id' => 5,
            ],
            [
                'same_time_from' => '0',
                'previous_status_id' => 248,
                'from_status_id' => 251,
                'active' => '1',
                'same_time' => '0',
                'workflow_type' => '0',
                'to_status_label' => null,
                'created_at' => '2025-12-31 23:44:47',
                'updated_at' => '2025-12-31 23:44:47',
                'type_id' => 5,
            ],
            [
                'same_time_from' => '0',
                'previous_status_id' => 251,
                'from_status_id' => 249,
                'active' => '1',
                'same_time' => '0',
                'workflow_type' => '0',
                'to_status_label' => 'approved',
                'created_at' => '2025-12-31 23:50:56',
                'updated_at' => '2025-12-31 23:50:56',
                'type_id' => 5,
            ],
            [
                'same_time_from' => '0',
                'previous_status_id' => 251,
                'from_status_id' => 249,
                'active' => '1',
                'same_time' => '0',
                'workflow_type' => '0',
                'to_status_label' => 'Need Update',
                'created_at' => '2025-12-31 23:51:55',
                'updated_at' => '2025-12-31 23:51:55',
                'type_id' => 5,
            ],
            [
                'same_time_from' => '0',
                'previous_status_id' => 256,
                'from_status_id' => 255,
                'active' => '1',
                'same_time' => '1',
                'workflow_type' => '0',
                'to_status_label' => 'Not valid',
                'created_at' => '2026-01-01 00:23:25',
                'updated_at' => '2026-01-01 09:39:46',
                'type_id' => 5,
            ],
            [
                'same_time_from' => '0',
                'previous_status_id' => 256,
                'from_status_id' => 255,
                'active' => '1',
                'same_time' => '1',
                'workflow_type' => '0',
                'to_status_label' => 'CR Doc Valid',
                'created_at' => '2026-01-01 00:23:33',
                'updated_at' => '2026-01-01 09:39:17',
                'type_id' => 5,
            ],
            [
                'same_time_from' => '0',
                'previous_status_id' => 255,
                'from_status_id' => 254,
                'active' => '1',
                'same_time' => '0',
                'workflow_type' => '0',
                'to_status_label' => 'CR Doc Not Approved',
                'created_at' => '2026-01-01 10:09:43',
                'updated_at' => '2026-01-01 10:09:43',
                'type_id' => 5,
            ],
            [
                'same_time_from' => '0',
                'previous_status_id' => 254,
                'from_status_id' => 256,
                'active' => '1',
                'same_time' => '0',
                'workflow_type' => '0',
                'to_status_label' => null,
                'created_at' => '2026-01-01 10:12:48',
                'updated_at' => '2026-01-01 10:12:48',
                'type_id' => 5,
            ],
            [
                'same_time_from' => '0',
                'previous_status_id' => 259,
                'from_status_id' => 260,
                'active' => '1',
                'same_time' => '0',
                'workflow_type' => '0',
                'to_status_label' => null,
                'created_at' => '2026-01-01 10:41:49',
                'updated_at' => '2026-01-01 10:41:49',
                'type_id' => 5,
            ],
            [
                'same_time_from' => '0',
                'previous_status_id' => 258,
                'from_status_id' => 260,
                'active' => '1',
                'same_time' => '0',
                'workflow_type' => '0',
                'to_status_label' => null,
                'created_at' => '2026-01-01 10:46:07',
                'updated_at' => '2026-01-01 10:46:07',
                'type_id' => 5,
            ],
            [
                'same_time_from' => '0',
                'previous_status_id' => 259,
                'from_status_id' => 267,
                'active' => '1',
                'same_time' => '0',
                'workflow_type' => '0',
                'to_status_label' => 'approved',
                'created_at' => '2026-01-01 11:01:49',
                'updated_at' => '2026-01-01 11:01:49',
                'type_id' => 5,
            ],
            [
                'same_time_from' => '0',
                'previous_status_id' => 259,
                'from_status_id' => 267,
                'active' => '1',
                'same_time' => '0',
                'workflow_type' => '0',
                'to_status_label' => null,
                'created_at' => '2026-01-01 11:07:01',
                'updated_at' => '2026-01-01 11:07:01',
                'type_id' => 5,
            ],
            [
                'same_time_from' => '0',
                'previous_status_id' => 259,
                'from_status_id' => 267,
                'active' => '1',
                'same_time' => '0',
                'workflow_type' => '0',
                'to_status_label' => 'not approved',
                'created_at' => '2026-01-01 11:12:31',
                'updated_at' => '2026-01-01 11:12:31',
                'type_id' => 5,
            ],
            [
                'same_time_from' => '0',
                'previous_status_id' => 267,
                'from_status_id' => 263,
                'active' => '1',
                'same_time' => '0',
                'workflow_type' => '0',
                'to_status_label' => 'approved from cr team',
                'created_at' => '2026-01-01 15:48:13',
                'updated_at' => '2026-01-01 15:48:13',
                'type_id' => 5,
            ],
            [
                'same_time_from' => '0',
                'previous_status_id' => 267,
                'from_status_id' => 263,
                'active' => '1',
                'same_time' => '0',
                'workflow_type' => '0',
                'to_status_label' => null,
                'created_at' => '2026-01-01 15:49:11',
                'updated_at' => '2026-01-01 15:49:11',
                'type_id' => 5,
            ],
            [
                'same_time_from' => '0',
                'previous_status_id' => 267,
                'from_status_id' => 262,
                'active' => '1',
                'same_time' => '0',
                'workflow_type' => '0',
                'to_status_label' => null,
                'created_at' => '2026-01-01 15:57:12',
                'updated_at' => '2026-01-01 15:57:12',
                'type_id' => 5,
            ],
        ];

        // Insert the data
        DB::table('new_workflow')->insert($data);
    }
}